action fix

diff --git a/.github/workflows/domains-validation.yml b/.github/workflows/domains-validation.yml
--- a/.github/workflows/domains-validation.yml
+++ b/.github/workflows/domains-validation.yml
@@ -1,80 +1,73 @@
 name: Domains validation
-
-on:
+'on':
   pull_request:
     branches:
       - main
-  workflow_dispatch:
-
+  workflow_dispatch: null
 jobs:
   check-for-duplicates:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-    - name: Find duplicate domains
-      run: |
-        set -e
-        jq -r '.programs[].domains[]' chaos-bugbounty-list.json | sort | uniq -c | awk '$1 > 1 { print $2 }' > duplicates.txt
-        if [[ -s duplicates.txt ]]; then
-            echo "Duplicate domains found: $(cat duplicates.txt)"
-            exit 1
-        else
-            echo "No duplicate domains found."
-        fi
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Find duplicate domains
+        run: >
+          set -e
 
+          jq -r '.programs[].domains[]' chaos-bugbounty-list.json | sort | uniq
+          -c | awk '$1 > 1 { print $2 }' > duplicates.txt
+
+          if [[ -s duplicates.txt ]]; then
+              echo "Duplicate domains found: $(cat duplicates.txt)"
+              exit 1
+          else
+              echo "No duplicate domains found."
+          fi
   check-invalid-domains:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Setup golang
-      uses: actions/setup-go@v3
-      with:
-        go-version: 1.19
-
-    - name: Installing Validate domains binary
-      run: |
-        go install github.com/projectdiscovery/public-bugbounty-programs/cmd/validate-domains
-      shell: bash
-
-    - name: Check domains validation
-      run: |
-        validate-domains -file chaos-bugbounty-list.json
-      shell: bash
-
-    - name: Return invalid if present
-      run: |
-        if [[ -s invalid_domains.txt ]]; then
-            echo "Invalid domains found: $(cat invalid_domains.txt)"
-            exit 1
-        fi
-      
-  check-for-duplicates:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Setup golang
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.19
+      - name: Installing Validate domains binary
+        run: >
+          go install
+          github.com/projectdiscovery/public-bugbounty-programs/cmd/validate-domains
+        shell: bash
+      - name: Check domains validation
+        run: |
+          validate-domains -file chaos-bugbounty-list.json
+        shell: bash
+      - name: Return invalid if present
+        run: |
+          if [[ -s invalid_domains.txt ]]; then
+              echo "Invalid domains found: $(cat invalid_domains.txt)"
+              exit 1
+          fi
+  httpx-check:
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
-
-    - name: Setup golang
-      uses: actions/setup-go@v3
-      with:
-        go-version: 1.19
-
-    - name: Installing Validate domains binary
-      run: |
-        go install github.com/projectdiscovery/public-bugbounty-programs/cmd/httpx-tester
-      shell: bash
-
-    - name: Check domains validation
-      run: |
-        httpx-tester -file chaos-bugbounty-list.json
-      shell: bash
-
-    - name: 
-      run: |
-        if [[ -s invalid.txt ]]; then
-            echo "Invalid domains found: $(cat invalid.txt)"
-            exit 1
-        fi
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Setup golang
+        uses: actions/setup-go@v3
+        with:
+          go-version: 1.19
+      - name: Installing Validate domains binary
+        run: >
+          go install
+          github.com/projectdiscovery/public-bugbounty-programs/cmd/httpx-tester
+        shell: bash
+      - name: Check domains validation
+        run: |
+          httpx-tester -file chaos-bugbounty-list.json
+        shell: bash
+      - name: null
+        run: |
+          if [[ -s invalid.txt ]]; then
+              echo "Invalid domains found: $(cat invalid.txt)"
+              exit 1
+          fi
